<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DepotDownloader</RootNamespace>
    <AssemblyName>BlueStar.DepotDownloader</AssemblyName>
    <Version>4.0.0</Version>
    <Description>Steam Depot Download Engine for BlueStar</Description>
    <Authors>SteamRE Team, BlueStar</Authors>
    <Copyright>Copyright © SteamRE Team 2025</Copyright>
    <Deterministic>true</Deterministic>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);IDE0055;IDE0044;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8620;CS8625;CS8767</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Link="LICENSE">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="protobuf-net" Version="3.2.52" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SteamKit2" Version="3.2.0" />
  </ItemGroup>
</Project>
